sudo: false
language: clojure
lein: 2.8.1
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk11   # Don't fall for Oracle's trick: https://blog.joda.org/2018/09/do-not-fall-into-oracles-java-11-trap.html

env:
  global:
    # CLOJARS_USERNAME
    - secure: "N+JdI9AO2LG5thGVf2sFkkb1cd69k6wwdH/lhZ9ewXTy/tHLqWBIOrvP2MyOWkcsfjZlePztejOA9ZSojlOC6Zo604Mb8ps5GKCld4nj8L9QzIQvcyNFqCtLQmmD4bZXiY/IztLgfwWOGIxyZlFH7xabC89vi5dq2VTJ+MR5Pxz4KEqMB7j0gegKoiKChbeQzpYkCiniJsnL7BhtVv47rOXmCwJPymXsmihA81CQpI70kj76R+hLcWk2A6021msInxYlkk+SeDzfK+qveG5RvyuZL8ChT74QI6ncEDy6NDc2WK5j7eItJVCd0JLp/tYpNgXZm6VSu19nuA4l9/BOsmfvdC4+Pgm27VyCDtw41qthEgZ0AOFwVdAatQyNtyTh7OaUqWAiDO4nk6NaMbmDBVfbNBphLgkCy6328BA4Ws2iQhSGECp9kU0xyBhWEZrPSlqb5yhLy+JGbNRDta5FJOzULU1svDExl+oEi5qmBpYiTMvDxkAM07FrXD4o0YXtPC5lNt15JzNhLua44udQUyU6F0irNSYYBsgAWi+oATq2yf5tZiQy61UaOIJtaFkBZd2dAlMA/VftOk+la7wmJgjXxyLnwxVTRFSWgCr5vxtpVON9/27RDt7E6TIAOzaLwdbiK0xeVuIN2bRnGTyohh4/LdFzIrGHIEdBjhMcPbM="
    # CLOJARS_PASSWORD
    - secure: "Gv3e1IW/dLUcgUnE85NK+C7aeipF5rW5HSaLsE8zZp5VjsYx+qKsCykacSPNZ6/aXga3Z/dzqpedOFyTDzvBCbCo6JK/GJna3TGxx3ftkBm77HE8+KfvwFfbIUmGjiYf5yFgnXM7vzr4sfiqVUYy0h+wJ1d245JMyMLUOTsM435gJ9Zu08NHFiDqYLVC05cC46G+t0xozzSxbMkg4l8+uvm+Cnx0qAfsjz/b3keyonCVvXMpbOYg4AbHSjzlD4v7NNJmg+2LJPBJjX7yrwEF5Yv++ZOuUPgJW5Hv2FcbAfxM+UHiFRsG8LNVOzkPErl8c0SvbhOONsYfXxdfX9UVJSlKvQ56TI0QEMCd4aW6oe15jDZpz3J3L5zgODcBv26AvCc4qpI5BKvyak0aEUbN8MvnWUq8z7jPUpfGXPqa2JeIG254+VSjtof6Hxd8WYx15dEhFh7ZPlxFKYW69aiicJ8F5+S9quk/f0O/nqKQ+wJX6G6QQcAp/Vnoywb153tYHtsrLb8/EOugTqgtKxJESUlJ41t7S0Rf//mOXGDri4mYT52qzFPecyMMNUrkqkFToT/7YeqpLT78MdEzP9c/dgXSOOR9dMQb668Pg85J72odzLXyYIXPubObuLktVGFLS9ouSjudbZjz0H3CsJ0B3G0S1ck3NplQhzuNfhSV+Io="
    # GITHUB_TOKEN
    - secure: "aTiUUQ4grdToG4s3RBO/b3+jdGPfqoDQBsZqEH8c4dQqEZiOaSeU59h9ik+4qmvrHP+BYlD1PdjOVeMxiZpZDL7/L0nUlhxjzYHlnB9csTpQuV+PbKQIiv5W4viqm4ESAW/k0lXDsAHwiGOu5XafCpPLzUBIPYxP01Y+nYNdDzT6Sd9JyLUTT7ynJujBvCdP0B7p83N2VQ9PZOL7p3lb0YeXjMNWBNtbqFwiUyE9Dyt5O09DQVkNRbzss6jL0rm1lTS/TlbuXoAo6zj2mIxi0ycRZi4AuHcAqq2A+PqC2WCT/uw9ue5qyVzqlnzBtLgPEYRrE/sKb1iiSxlz4YlwpbKg8Yf9AS7hntkW2Zj6vuAM5APS8AiJhsKqa9f31IgdtwnY6sytgXJ4uAXskWNAAzSYoiTBjJ+n2VC5uatSKSSWRZX0xlPDVkOqo35CQma7Xwnri2tGIT0A+3xYPzI0p3/fB0ChGBMzvYrKcMnv/prYJebCOhCN+fn2Q4IXQ7Q0MOFTtvuAZAkoyqiPWi/NGAml/JM8pruNZMPAurZEpXkf+XKlXZaF1kLGNE99ujAeBiYjiR/g23pt8Hb/tGOCKWElsNdj4ny2XoYYZtBNNM3297DrEyP0MrbL9VYHrrb/Szi1TcGTuF6H6EhjzxwtsGsntyG4mXcxg8HnkUjx1xI="

script:
  - export PROFILES=+1.5:+1.6:+1.7:+1.8:+1.9
  - if [[ $JAVA_HOME != *java-7* ]]; then export PROFILES=${PROFILES}:+1.10; fi
  - lein with-profile ${PROFILES} do version, check, test

deploy:
  # Deploy binaries to Clojars
  - provider: script
    skip_cleanup: true
    script: lein deploy
    on:
      branch: master
      jdk: openjdk11
  # Generate documentation
  - provider: script
    skip_cleanup: true
    script: lein codox
    on:
      branch: master
      jdk: openjdk11
  # Deploy documentation
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    email: pmonks+travisci@gmail.com
    name: Travis CI - pmonks
    local_dir: target/doc
    on:
      branch: master
      jdk: openjdk11
